language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-21.1.0
    - android-21
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

before_install: export TERM=dumb

script: ./gradlew build check

branches:
  only:
    - master
    - production

# after_success: uncomment this and add your own deployment targets