language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - build-tools-19.1
    - android-19
    - extra-android-m2repository

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export TERM=dumb

branches:
  only:
    - master