language: android

android:
  components:
    - build-tools-20.0.0
    - android-20
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5

before_install: export TERM=dumb

script: ./gradlew build check

branches:
  only:
    - master
    - integration

after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./gradlew -PtestfairyChangelog="$(git log -1 --pretty=%B)" testfairyStagingRelease testfairyProductionTestfairy'